/* JobSeek Unified Application Engine */
(function(){
'use strict';
const KEY='jobseek_unified_engine_v1';
const STATES=['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara','Federal Capital Territory'];
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}};
const write=x=>localStorage.setItem(KEY,JSON.stringify(x));
const text=v=>Array.isArray(v)?v.join(' '):String(v||'');
const clean=v=>text(v).toLowerCase().replace(/[^a-z0-9+#.]+/g,' ').replace(/\s+/g,' ').trim();
const unique=a=>[...new Set(a.filter(Boolean))];
function profileCompleteness(p={}){const keys=['full_name','phone','country_of_residence','city','profession','target_job','education','availability'];let n=keys.filter(k=>text(p[k]).trim()).length;n+=Array.isArray(p.skills)&&p.skills.length?1:0;n+=Array.isArray(p.languages)&&p.languages.length?1:0;n+=Array.isArray(p.preferred_countries)&&p.preferred_countries.length?1:0;n+=Array.isArray(p.preferred_job_types)&&p.preferred_job_types.length?1:0;return Math.round(n/12*100)}
function analyzeJob(job={},p={}){const blob=clean([job.title,job.description,job.requirements,job.category,job.location,job.country].join(' '));const skills=Array.isArray(p.skills)?p.skills.map(clean):[];const matched=skills.filter(s=>s&&blob.includes(s));const skillScore=skills.length?Math.round(matched.length/skills.length*100):0;const location=job.remote?100:(p.preferred_states||[]).some(s=>clean(job.location).includes(clean(s)))?100:60;const experience=Number(p.years_experience||0)>0?100:50;const visa=job.visa_sponsorship?80:60;const score=Math.max(0,Math.min(100,Math.round(skillScore*.45+experience*.25+location*.15+visa*.15)));return{score,skillScore,experience,location,visa,matched,missing:[]}}
function buildPack(job,p,a){const name=p.full_name||'Candidate';const title=job.title||p.target_job||'Target Role';return{cv:name+'\n'+(p.profession||title)+'\n\nCORE SKILLS\n'+(p.skills||[]).join(' · ')+'\n\nEXPERIENCE\n'+(p.experience||'Add verified employment history.'),letter:'Dear Hiring Manager,\n\nI am applying for the '+title+' position at '+(job.company||'your organisation')+'. My background and verified experience align with this vacancy.\n\nKind regards,\n'+name,interview:['Tell me about yourself.','Which experience is most relevant to this role?','Describe a problem you solved.','Why do you want this role?'],checklist:['Review CV for accuracy','Review cover letter','Confirm required documents','Confirm application deadline','Verify official application URL','Save submission confirmation']}}
async function persistApplication(client,userId,job,pack,analysis){const state=read();state.applications=state.applications||{};const id=String(job.id||job.title||Date.now());state.applications[id]={job,analysis,pack,status:'preparing',updatedAt:new Date().toISOString()};write(state);if(client&&userId){const r=await client.from('jobseek_application_workflows').upsert({user_id:userId,external_job_id:String(job.id||''),status:'preparing',match_score:analysis.score,analysis:analysis,tailored_cv:pack.cv,cover_letter:pack.letter,interview_plan:pack.interview,checklist:pack.checklist,application_url:job.apply_url||job.direct_application_url||null},{onConflict:'user_id,external_job_id'});return r.error?{ok:false,error:r.error.message}:{ok:true}}return{ok:true,local:true}}
window.JobSeekEngine={STATES,read,write,profileCompleteness,analyzeJob,buildPack,persistApplication};
})();